name: MagicPortalsPE
main: luca28pet\PortalsPE\Main
api: 4.0.0
version: 2.0.0
authors: ["luca28pet", "pushkar"]
description: A portals plugin
permissions:
  portalspe:
    default: false
  portalspe.cmd:
    default: op
