name: BurgerSellWands
main: Heisenburger69\BurgerSellWands\Main
version: 2.0.0
api: 4.0.0
authors: [Heisenburger69, AGTHARN]
description: Plugin implements fully customizable BurgerSellWands for PMMP

commands:
  sellwand:
    description: Give sell wands to a player
    aliases:
    - sw
    - burgersellwand
    permission: sellwand.command
permissions:
  sellwand.command:
    default: op
    description: Allows the use of /sellwand
  sellwand.use:
    default: true
    description: Allows player use Sell Wands on Chests