NonAdminChat:
- Before: "§"
  After: ""
Emoji:
  - Before: ":sword:"
    After: ""
  - Before: ":skull:"
    After: ""
  - Before: ":earth:"
    After: ""
  - Before: ":portal:"
    After: ""
  - Before: ":dice:"
    After: ""
  - Before: ":candy:"
    After: ""
  - Before: ":crown:"
    After: ""
  - Before: ":star:"
    After: ""
  - Before: ":diamond:"
    After: ""
  - Before: ":bruh:"
    After: ""
  - Before: ":hehe:"
    After: ""
  - Before: ":ooo:"
    After: ""
  - Before: ":cry:"
    After: ""
  - Before: ":stare:"
    After: ""
  - Before: ":happy:"
    After: ""
  - Before: ":angry:"
    After: ""
  - Before: ":hmm:"
    After: ""
  - Before: ":sus:"
    After: ""