main : AGTHARN\BankUI\Main
name: BankUI
version: 4.0.0
api: 4.0.0
author: AGTHARN
depend: [EconomyAPI]

permissions:
  bankui.admin:
    description: Permission to view other players bank
    default: op
  bankui.cmd:
    description: Permission to open bank ui
    default: true
