 #Discord Moderation
log-player-webhook: true
log-webhook-url: "https://discord.com/api/webhooks/966717375191859310/kPWT5qvRsoEZhXnioBmunDcy3yXplsNrDS7rZP-TUSTjLanSLaAI9wbDlTRKdPXVxNKd"
log-embed-color: "FFBF00"
log-webhook-username: "MagicGames-Bank-Log"
log-webhook-avatar-url: "https://cdn-icons-png.flaticon.com/128/2830/2830289.png"
log-thumbnail-url: "https://cdn-icons-png.flaticon.com/128/2830/2830289.png"

# DO NOT TOUCH
config-ver: 1

# If true, players will get daily interest for the money in their bank
enable-interest: true

# Interst Rates is in percentage so if interst-rates = 50, it means 50% Interest Rates, if it is set at 1, it means 1% interest rates. (It is recommended to keep this low)
interest-rates: 1
